[package]
name = "kawa-rs"
version = "0.0.1"
authors = ["koopa1338 <sinner1991@gmail.com>"]
edition = "2021"

[dependencies]
reqwest = { version = "0.11.6", features = ["cookies"] }
tokio = { version = "1.12.0", features = ["full"] }
druid = { version = "0.7.0", features = ["im"] }

[profile.release]
lto = true
