[package]
name = "kawa-rs"
version = "0.0.1"
authors = ["koopa1338 <sinner1991@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.4", features = ["cookies"] }
tokio = { version = "0.2", features = ["full"] }

[profile.release]
lto = true
