[package]
name = "kawa-rs"
version = "0.0.1"
authors = ["koopa1338 <sinner1991@gmail.com>"]
edition = "2021"

[dependencies]
eframe = { version = "0.16.0", features = ["persistence"] }
reqwest = { version = "0.11.6", features = ["cookies"] }
rfd = "0.7.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tokio = { version = "1.12.0", features = ["full"] }

[profile.release]
lto = true
